
enum TWriterThreadReplyType: int {
    REPLY_BROADCAST=0,
    REPLY_DIRECT=1,
    REPLY_LOGOUT=2
};

enum TWriterThreadOrderType: int {
    ORDER_TERMINATE=0,
    ORDER_LOGOUT=1,
    ORDER_PLAYERLIST=2,
    ORDER_KILLSTATISTICS=3,
    ORDER_PUNISHMENT=4,
    ORDER_CHARACTERDEATH=5,
    ORDER_ADDBUDDY=6,
    ORDER_REMOVEBUDDY=7,
    ORDER_DECREMENTISONLINE=8,
    ORDER_SAVEPLAYERDATA=9
};

enum CHANNEL: int {
    GUILD_CHANNEL=0,
    GAMEMASTER_CHANNEL=1,
    TUTOR_CHANNEL=2,
    REQUEST_QUEUE=3,
    GAME_CHANNEL=4,
    TRADE_CHANNEL=5,
    REALLIFE_CHANNEL=6,
    HELP_CHANNEL=7
};

enum TReaderThreadOrderType: int {
    ORDER_TERMINATE=0,
    ORDER_LOADSECTOR=1,
    ORDER_LOADCHARACTER=2
};

enum TReaderThreadReplyType: int {
    REPLY_SECTORDATA=0,
    REPLY_CHARACTERDATA=1
};
