enum CHANNEL: int {
    GUILD_CHANNEL=0,
    GAMEMASTER_CHANNEL=1,
    TUTOR_CHANNEL=2,
    REQUEST_QUEUE=3,
    GAME_CHANNEL=4,
    TRADE_CHANNEL=5,
    REALLIFE_CHANNEL=6,
    HELP_CHANNEL=7
};

enum TReaderThreadOrderType: int {
    ORDER_TERMINATE=0,
    ORDER_LOADSECTOR=1,
    ORDER_LOADCHARACTER=2
};

enum TReaderThreadReplyType: int {
    REPLY_SECTORDATA=0,
    REPLY_CHARACTERDATA=1
};
