
enum STATE: int {
    SLEEPING=0,
    IDLE=1,
    UNDERATTACK=2,
    TALKING=3,
    LEAVING=4,
    ATTACKING=5,
    PANIC=6
};

enum ActionType: int {
    ACTION_CREATEONMAP=0,
    ACTION_CREATE=1,
    ACTION_MONSTERONMAP=2,
    ACTION_MONSTER=3,
    ACTION_EFFECTONMAP=4,
    ACTION_EFFECT=5,
    ACTION_TEXTONMAP=6,
    ACTION_TEXT=7,
    ACTION_CHANGEONMAP=8,
    ACTION_CHANGE=9,
    ACTION_CHANGEREL=10,
    ACTION_SETATTRIBUTE=11,
    ACTION_CHANGEATTRIBUTE=12,
    ACTION_SETQUESTVALUE=13,
    ACTION_DAMAGE=14,
    ACTION_SETSTART=15,
    ACTION_WRITENAME=16,
    ACTION_WRITETEXT=17,
    ACTION_LOGOUT=18,
    ACTION_MOVEALLONMAP=19,
    ACTION_MOVEALL=20,
    ACTION_MOVEALLREL=21,
    ACTION_MOVETOPONMAP=22,
    ACTION_MOVETOP=23,
    ACTION_MOVETOPREL=24,
    ACTION_MOVE=25,
    ACTION_MOVEREL=26,
    ACTION_RETRIEVE=27,
    ACTION_DELETEALLONMAP=28,
    ACTION_DELETETOPONMAP=29,
    ACTION_DELETEONMAP=30,
    ACTION_DELETE=31,
    ACTION_DELETEININVENTORY=32,
    ACTION_DESCRIPTION=33,
    ACTION_LOADDEPOT=34,
    ACTION_SAVEDEPOT=35,
    ACTION_SENDMAIL=36,
    ACTION_NOP=37
};

enum ModifierType: int {
    MODIFIER_NORMAL=0,
    MODIFIER_INVERT=1,
    MODIFIER_TRUE=2
};

enum ConditionType: int {
    CONDITION_ISPOSITION=0,
    CONDITION_ISTYPE=1,
    CONDITION_ISCREATURE=2,
    CONDITION_ISPLAYER=3,
    CONDITION_HASFLAG=4,
    CONDITION_HASTYPEATTRIBUTE=5,
    CONDITION_HASINSTANCEATTRIBUTE=6,
    CONDITION_HASTEXT=7,
    CONDITION_ISPEACEFUL=8,
    CONDITION_MAYLOGOUT=9,
    CONDITION_HASPROFESSION=10,
    CONDITION_HASLEVEL=11,
    CONDITION_HASRIGHT=12,
    CONDITION_HASQUESTVALUE=13,
    CONDITION_TESTSKILL=14,
    CONDITION_COUNTOBJECTS=15,
    CONDITION_COUNTOBJECTSONMAP=16,
    CONDITION_ISOBJECTTHERE=17,
    CONDITION_ISCREATURETHERE=18,
    CONDITION_ISPLAYERTHERE=19,
    CONDITION_ISOBJECTININVENTORY=20,
    CONDITION_ISPROTECTIONZONE=21,
    CONDITION_ISHOUSE=22,
    CONDITION_ISHOUSEOWNER=23,
    CONDITION_ISDRESSED=24,
    CONDITION_RANDOM=25
};

enum TWriterThreadReplyType: int {
    REPLY_BROADCAST=0,
    REPLY_DIRECT=1,
    REPLY_LOGOUT=2
};

enum TWriterThreadOrderType: int {
    ORDER_TERMINATE=0,
    ORDER_LOGOUT=1,
    ORDER_PLAYERLIST=2,
    ORDER_KILLSTATISTICS=3,
    ORDER_PUNISHMENT=4,
    ORDER_CHARACTERDEATH=5,
    ORDER_ADDBUDDY=6,
    ORDER_REMOVEBUDDY=7,
    ORDER_DECREMENTISONLINE=8,
    ORDER_SAVEPLAYERDATA=9
};

enum CHANNEL: int {
    GUILD_CHANNEL=0,
    GAMEMASTER_CHANNEL=1,
    TUTOR_CHANNEL=2,
    REQUEST_QUEUE=3,
    GAME_CHANNEL=4,
    TRADE_CHANNEL=5,
    REALLIFE_CHANNEL=6,
    HELP_CHANNEL=7
};

enum EventType: int {
    EVENT_USE=0,
    EVENT_MULTIUSE=1,
    EVENT_MOVEMENT=2,
    EVENT_COLLISION=3,
    EVENT_SEPARATION=4
};

enum ParameterType: int {
    PARAMETER_OBJECT=0,
    PARAMETER_TYPE=1,
    PARAMETER_FLAG=2,
    PARAMETER_TYPEATTRIBUTE=3,
    PARAMETER_INSTANCEATTRIBUTE=4,
    PARAMETER_COORDINATE=5,
    PARAMETER_VECTOR=6,
    PARAMETER_RIGHT=7,
    PARAMETER_SKILL=8,
    PARAMETER_NUMBER=9,
    PARAMETER_TEXT=10,
    PARAMETER_COMPARISON=11
};

enum TReaderThreadOrderType: int {
    ORDER_TERMINATE=0,
    ORDER_LOADSECTOR=1,
    ORDER_LOADCHARACTER=2
};

enum TReaderThreadReplyType: int {
    REPLY_SECTORDATA=0,
    REPLY_CHARACTERDATA=1
};

enum SITUATION: int {
    DEFAULT=0,
    ADDRESS=1,
    ADDRESSQUEUE=2,
    BUSY=3,
    VANISH=4
};
